# Default values for aaf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  persistence:
    enabled: true
  common:
    namespace: onap

ingress:
  enabled: false

cadi:
  hostname: "aaf.onap"
  cadi_latitude: "38.0"  
  cadi_longitude: "-72.0"  
  aaf_env: "DEV"
  aaf_register_as: "aaf.onap"

persistence:
  mountPath: "/mnt/data/aaf"
  config:
    volumeReclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 2Gi
    mountSubPath: "config"
    storageClass: "manual"
  status:
    volumeReclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 10M
    mountSubPath: "status"
    storageClass: "manual"
  cass:
    volumeReclaimPolicy: Retain
    accessMode: ReadWriteOnce
    size: 10Gi
    mountSubPath: "cass"
    storageClass: "manual"

image:
  # When using locally built Docker Container, set Repository to ""
  repository: ""
  # When using Docker Repo, add, and include trailing "/"
  # repository: nexus3.onap.org:10003/
  # repository: localhost:5000/
  version: 2.1.2-SNAPSHOT

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
