#########
##  ============LICENSE_START====================================================
##  org.onap.aaf
##  ===========================================================================
##  Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
##  ===========================================================================
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.
##  ============LICENSE_END====================================================
##
###
### AAF-CERTMAN
###
kind: Service
apiVersion: v1
metadata:
  name: aaf-cm
spec:
  selector:
    app: aaf-cm
  type: NodePort
  ports:
    - name: aaf-cm
      protocol: TCP
      port: 8150
      nodePort: 30084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-cm
  labels:
    app: aaf-cm
spec:
  replicas: {{ .Values.services.cm.replicas }}
  selector:
    matchLabels:
      app: aaf-cm
  template:
    metadata:
      labels:
        app: aaf-cm
    spec:
      volumes:
        # Use this Pod Sharing dir to declare various States of starting
      - name: aaf-config-vol
        persistentVolumeClaim:
          claimName: aaf-config-pvc
      - name: aaf-status-vol
        persistentVolumeClaim:
          claimName: aaf-status-pvc
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              chmod -R 775 /opt/app/aaf/status
              chown -R 1000:1000 /opt/app/aaf/status
              chmod -R 775 /opt/app/osaaf
              chown -R 1000:1000 /opt/app/osaaf
          image: busybox:1.28
          imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.pullPolicy }}
          name: init-sysctl
          volumeMounts:
            - mountPath: /opt/app/aaf/status
              name: aaf-status-vol
            - mountPath: /opt/app/osaaf
              name: aaf-config-vol
        - name: aaf-config-container
          image: {{ .Values.image.repository }}onap/aaf/aaf_config:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          command: ["bash","-c","cd /opt/app/aaf_config && bin/pod_wait.sh config aaf-service rm "]
          volumeMounts:
            - mountPath: "/opt/app/aaf/status"
              name: aaf-status-vol
      containers:
###
### AAF-CERTMAN
###
      - name: aaf-cm
        image: {{ .Values.image.repository }}onap/aaf/aaf_core:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c","cd /opt/app/aaf && /bin/bash bin/pod_wait.sh aaf-cm nc aaf-cass.{{ .Release.Namespace }} {{ .Values.services.cass.native_trans_port }} aaf-locate && exec bin/cm"]
        volumeMounts:
        -  mountPath: "/opt/app/osaaf"
           name: aaf-config-vol
        -  mountPath: "/opt/app/aaf/status"
           name: aaf-status-vol
        ports:
        - name: aaf-cm
          protocol: TCP
          containerPort: 8150
        env:
        - name: aaf_locator_ns
          value: {{ .Release.Namespace }}
