kind: Service
apiVersion: v1
metadata:
  name: aaf
spec:
  selector:
    app: aaf
  #type: ExternalName
  #externalName: aaf.osaaf.org
  externalIPs:
  - 192.168.99.100
  ports:
    - name: aaf-service
      protocol: TCP
      port: 8100
      targetPort: 8100
    - name: aaf-locate
      protocol: TCP
      port: 8095
      targetPort: 8095
    - name: aaf-oauth
      protocol: TCP
      port: 8140
      targetPort: 8140
    - name: aaf-gui
      protocol: TCP
      port: 8200
      targetPort: 8200
    - name: aaf-cm
      protocol: TCP
      port: 8150
      targetPort: 8150
    - name: aaf-hello
      protocol: TCP
      port: 8130
      targetPort: 8130
    - name: aaf-fs
      protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-svcs
  labels:
    app: aaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaf
  template:
    metadata:
      labels:
        app: aaf
    spec:
      volumes:
      - name: {{ .Chart.Name }}-config-vol
        persistentVolumeClaim:
        claimName: {{ .Chart.Name }}-config-pvc
      # Use this Pod Sharing dir to declare various States of starting
      - name: {{ .Chart.Name }}-status-vol
        persistentVolumeClaim:
        claimName: {{ .Chart.Name }}-status-pvc
      initContainers:
        - name: {{ .Chart.Name }}-config-container
          image: {{ .Values.image.repository }}onap/aaf/aaf_config:{{ .Values.image.version }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
          env:
            - name: HOSTNAME
              value: "{{ .Values.cadi.hostname }}"
            - name: AAF_ENV
              value: "{{ .Values.cadi.aaf_env }}"
            - name: AAF_REGISTER_AS
              value: "{{ .Values.cadi.aaf_register_as }}"
            - name: LATITUDE
              value: "{{ .Values.cadi.cadi_latitude }}"
            - name: LONGITUDE
              value: "{{ .Values.cadi.cadi_longitude }}"
            - name: CASS_HOST
              value: "aaf-cass"
      containers:
###
### AAF-Service
###
      - name: {{ .Chart.Name }}-service
        image: {{ .Values.image.repository }}onap/aaf/aaf_service:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_service","sleep","30","/opt/app/aaf/bin/service"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: service
          protocol: TCP
          containerPort: 8100
#          hostPort: 8100
###
### AAF-Locate
###
      - name: {{ .Chart.Name }}-locate
        image: {{ .Values.image.repository }}onap/aaf/aaf_locate:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_locate","aaf_service","/opt/app/aaf/bin/locate"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: locate
          protocol: TCP
          containerPort: 8095

###
### AAF-OAuth
###
      - name: {{ .Chart.Name }}-oauth
        image: {{ .Values.image.repository }}onap/aaf/aaf_oauth:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_oauth","aaf_locate","/opt/app/aaf/bin/oauth"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: oauth
          protocol: TCP
          containerPort: 8096
###
### AAF-GUI
###
      - name: {{ .Chart.Name }}-gui
        image: {{ .Values.image.repository }}onap/aaf/aaf_gui:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_gui","aaf_cm","/opt/app/aaf/bin/gui"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: gui
          protocol: TCP
          containerPort: 8200
###
### AAF-Certman
###
      - name: {{ .Chart.Name }}-cm
        image: {{ .Values.image.repository }}onap/aaf/aaf_cm:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_cm","aaf_locate","/opt/app/aaf/bin/cm"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: cm
          protocol: TCP
          containerPort: 8150

###
### AAF-FS
###
      - name: {{ .Chart.Name }}-fs
        image: {{ .Values.image.repository }}onap/aaf/aaf_fs:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_fs","aaf_locate","/opt/app/aaf/bin/fs"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: fs
          protocol: TCP
          containerPort: 8096

###
### AAF-Hello
###
      - name: {{ .Chart.Name }}-hello
        image: {{ .Values.image.repository }}onap/aaf/aaf_hello:{{ .Values.image.version }}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","/opt/app/aaf/pod/pod_wait.sh","aaf_hello","aaf_locate","/opt/app/aaf/bin/hello"]
        volumeMounts:
          - mountPath: "/opt/app/osaaf"
            name: {{ .Chart.Name }}-config-vol
          - mountPath: "/opt/app/aaf/status"
            name: {{ .Chart.Name }}-status-vol
        ports:
        - name: hello
          protocol: TCP
          containerPort: 8130

